JRD Validating webfinger

diff --git a/webfinger b/webfinger
--- a/webfinger
+++ b/webfinger
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
 # webfinger
 
+program=$0
+program_directory="$(dirname "$0")"
+
 if [ ! `which curl` ]
 then
     echo Installing 'curl'
@@ -17,6 +20,7 @@ set -euo pipefail
 
 rel=
 verbose=
+validate=
 
 rawurlencode() {
     local string="${1}"
@@ -39,14 +43,15 @@ rawurlencode() {
 usage() {
 >&2 cat << EOF
 Usage: $0
-    [ -v | --verbose ]
     [ -r | --rel | --REL input ]
+    [ -V | --validate ]
+    [ -v | --verbose ]
     <user@domain>
 EOF
 exit 1
 }
 
-args=$(getopt -a -o hvr: --long help,verbose,rel:,REL: -- "$@")
+args=$(getopt -a -o Vhvr: --long help,verbose,validate,json-ld,rel:,REL: -- "$@")
 if [[ $? -gt 0 ]]; then
   usage
 fi
@@ -57,6 +62,7 @@ do
   case $1 in
     -h | --help) usage; shift;;
     -v | --verbose) verbose=true; shift;;
+    -V | --validate) validate=true; shift;;
     -r | --rel | --REL) rel=$2; shift 2;;
     # -- means the end of the arguments; drop this, and break out of the while loop
     --) shift; break ;;
@@ -69,18 +75,25 @@ if [[ $# -eq 0 ]]; then
   usage
 fi
 
-name=`echo $1 | sed 's/\(.*\)@\(.*\)$/\1/'`
+name=`echo $1 | sed 's/@\(.*\)@\(.*\)$/\1/'`
 domain=`echo $1 | sed 's/\(.*\)@\(.*\)$/\2/'`
 server=$domain
 
 address=${name}@${domain}
 resource=acct:$(rawurlencode $address)
 
-if [ ! -n "${rel}" ]; then
-    command="curl -s -H \"Accept: application/jrd+json\" https://${server}/.well-known/webfinger?resource=${resource}"
+accept="Accept: application/jrd+json"
+
+base="https://${server}/.well-known/webfinger"
+
+if [ ! -n "${rel}" ];
+then
+    uri="${base}?resource=${resource}"
 else
-    command="curl -s -H \"Accept: application/jrd+json\" https://${server}/.well-known/webfinger?resource=${resource}&rel=${rel}"
+    uri="${base}?resource=${resource}&rel=${rel}"
 fi
+
+command="curl -s -H \"${accept}\" ${uri}"
 
 if [ -n "${verbose}" ]
 then
@@ -89,6 +102,30 @@ then
 fi
 
 result=`${command}`
-#echo ${result}
 
-echo $result | jq .
+if [ "${result}" != "" ];
+then
+    echo $result | jq .
+
+    if [ -n "${validate}" ]; then
+        if [ ! `which ajv` ];
+        then
+            if [ `which node` && `which npm` ];
+            then
+                npm install -g ajv-cli ajv-formats
+            else
+                echo "Error: node.js not installed"
+            fi
+        fi
+        if [ ! -e ${program_directory}/jrd.schema.json ]; then
+            curl -s https://raw.githubusercontent.com/AaronNGray/webfinger.sh/main/jrd.schema.json >${program_directory}/jrd.schema.json
+        fi
+        echo -e "${result}" >/tmp/out.json
+        echo
+        ajv --spec=draft2020 -c ajv-formats -s ${program_directory}/jrd.schema.json -d /tmp/out.json >null
+        if [ $? ]; then
+            echo "valid JRD"
+        fi
+        rm /tmp/out.json
+    fi
+fi
